<?xml version="1.0"?>
<robot name="limo_xacro" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="limo_wheel" params="parent_prefix wheel_prefix reflect *joint_pose">

    <link name="${wheel_prefix}_wheel_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.5" />
        <inertia ixx="0.01055" ixy="0" ixz="0"
                 iyy="0.00075" iyz="0"
                 izz="0.01055" />
      </inertial>

      <visual>
        <origin xyz="0 ${wheel_length/2} 0" rpy="1.5708 0 0" />
        <geometry>
          <cylinder length="${wheel_length}" radius="${wheel_radius}" />
        </geometry>
        <material name="${wheel_prefix}_material">
          <color rgba="0.0 0.0 0.0 1" />
        </material>
      </visual>

      <collision>
        <!-- Cylinder is rotated so its axis matches joint axis (Y) -->
        <origin xyz="0 ${wheel_length/2} 0" rpy="1.5708 0 0" />
        <geometry>
          <cylinder length="0.05" radius="${wheel_radius}" />
        </geometry>
      </collision>
    </link>

    <joint name="${wheel_prefix}_wheel_joint" type="continuous">
      <parent link="${parent_prefix}" />
      <child link="${wheel_prefix}_wheel_link" />
      <xacro:insert_block name="joint_pose" />
      <!-- Wheel rotation axis in parent frame -->
      <axis xyz="0 ${reflect*1} 0" />
    </joint>
  </xacro:macro>

  <xacro:macro name="limo_laser" params="parent_prefix frame_prefix *joint_pose">
    <link name="${frame_prefix}_link">
      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="1e-6" ixy="0" ixz="0"
                 iyy="1e-6" iyz="0"
                 izz="1e-6" />
      </inertial>

      <visual name="${frame_prefix}_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="0.02" length="0.01" />
        </geometry>
        <!-- URDF material is okay, but Webots may ignore it; harmless -->
        <material name="${frame_prefix}_material">
          <color rgba="0.1 0.1 0.2 1" />
        </material>
      </visual>

      <collision name="${frame_prefix}_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="0.032" length="0.016" />
        </geometry>
      </collision>
    </link>

    <joint type="fixed" name="${frame_prefix}_joint">
      <xacro:insert_block name="joint_pose" />
      <parent link="${parent_prefix}" />
      <child link="${frame_prefix}_link" />
    </joint>
  </xacro:macro>

  <xacro:macro name="limo_depth_camera" params="parent_prefix frame_prefix *joint_pose">
        <link name='${frame_prefix}_link'>
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
                <inertia
                    ixx="1e-6" ixy="0" ixz="0"
                    iyy="1e-6" iyz="0"
                    izz="1e-6"/>
            </inertial>
            <visual name='depth_camera_visual'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.06 0.015"/>
                </geometry>
                <material name="${frame_prefix}_material">
                    <color rgba="0.3 0.1 0.1 1" />
                </material>
            </visual>
            <collision name='depth_camera_collision'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.06 0.015"/>
                </geometry>
            </collision>
        </link>
        <joint type="fixed" name="depth_camera_joint">
            <xacro:insert_block name="joint_pose"/>
            <child link="${frame_prefix}_link"/>
            <parent link="${parent_prefix}"/>
        </joint>
        <link name="depth_link"></link>
        <joint name="${frame_prefix}_to_camera_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2} "/>
            <parent link="${frame_prefix}_link"/>
            <child link="depth_link"/>
        </joint>
    </xacro:macro>


  <!-- ===================== -->
  <!-- IMU Frame Macro       -->
  <!-- (Frame + visual only) -->
  <!-- ===================== -->
  <xacro:macro name="limo_imu" params="parent_prefix frame_prefix *joint_pose">

    <link name="${frame_prefix}_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="1e-7" ixy="0" ixz="0"
                 iyy="1e-7" iyz="0"
                 izz="1e-7" />
      </inertial>

      <visual name="${frame_prefix}_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.01 0.01" />
        </geometry>
        <material name="${frame_prefix}_material">
          <color rgba="0.1 0.1 0.2 1" />
        </material>
      </visual>

      <collision name="${frame_prefix}_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
    </link>

    <joint type="fixed" name="${frame_prefix}_joint">
      <xacro:insert_block name="joint_pose" />
      <parent link="${parent_prefix}" />
      <child link="${frame_prefix}_link" />
    </joint>

  </xacro:macro>

</robot>
